# Site settings
title: Hazi Class Notes
subtitle: Template by HTML5 UP
email: yjgg@lasallistas.org.mx
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/hazi98
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: www.linkedin.com/in/jassiel-garcia
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
